### ISSUE TITLE
Interest in switching to box-sizing: border-box?

### ISSUE THREAD

**Issue by mankittens** [TryGhost/Casper#184]
I would do it like this:

```css
html {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}

*,
*:before,
*:after { /* Inherit box-sizing to make it easier overwrite */
    box-sizing: inherit;
}
```

But I would need to double-check the borders and padding on everything, of course. Just want to know if it's worth the effort.

Thanks!

**Comment by novaugust** [comment]
> Just want to know if it's worth the effort.

Can you tell us why it would be worth the effort? Doubt anyone's dying to change the code just to change the code :)

**Comment by mankittens** [comment]
Sorry. Should've given an explanation! :)

IMO, border-box makes managing element widths and heights a lot simpler by including the element's padding and border size into the width or height calculation.

(without)
```css
.box {
    /* designer must subtract border and padding size to achieve desired height and width. */
    height: 17px;
    width: 17px;
    border: 1px solid black;
    padding: 2px;
}
```

(with)
```css
.box {
    /* height and width are not dependent on border and padding size. */
    height: 20px;
    width: 20px;
    border: 1px solid black;
    padding: 2px;
}
```

And when it really comes through:

(without)
```css
.box {
    width: calc(100% - 4em);
    padding: 0 2em;
}
```

(with)
```css
.box {
    width: 100%;
    padding: 0 2em;
}
```

Just depends on the preference of the maintainers. ;)
