### ISSUE TITLE
.author-image misaligned

### ISSUE THREAD

**Issue by akshaybabloo** [TryGhost/Casper#276]
The author's image is misaligned when viewed on the desktop.

<img width="745" alt="screen shot 2016-10-23 at 12 39 37 pm" src="https://cloud.githubusercontent.com/assets/7360286/19623232/88877698-991e-11e6-8ef1-a206997ecb84.png">

Changing `top: -40` to `top: -60` does the trick.

Complete code:

``` css
.author-image {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    display: block;
    position: absolute;
    top: -60px;
    left: 50%;
    margin-left: -40px;
    width: 80px;
    height: 80px;
    border-radius: 100%;
    overflow: hidden;
    padding: 6px;
    background: #fff;
    z-index: 2;
    box-shadow: #E7EEF2 0 0 0 1px;
}
```
