### ISSUE TITLE
using vertical align in a block-level element

### ISSUE THREAD

**Issue by ezzarghili** [TryGhost/Casper#518]
https://github.com/TryGhost/Casper/blob/3388283f02d99bf29a6a691a6c771960b884a901/assets/css/screen.css#L1606

MDN docs state that `vertical-align` should only be used in inline-level element
> Note that vertical-align only applies to inline and table-cell elements: you can't use it to vertically align block-level elements.

Which is not the case in this block
```css
.read-next-card-content li a {
    display: block;
    padding: 20px 0;
    border-bottom: rgba(255,255,255,0.3) 1px solid;
    color: #fff;
    font-weight: 500;
    vertical-align: top;
    transition: opacity 0.3s ease;
}
```
as you can see we have `display: block` and `vertical-align: top`
