### ISSUE TITLE
Casper 2.9.0 bumped default Ghost API version to v2 leaded to blocked:mixed-content error in browser

### ISSUE THREAD

**Issue by ykfq** [TryGhost/Casper#540]
### Causing
  I'm using docker-compose running ghost, the previous version was 2.10 and I was planing to upgrade it to the newest version 2.16，I justin changed the image version and `docker-compose up -d` , then I refresh my blog and I found the uploaded images are missing, then I right click on the corrupted image, selected `open image in new tab` found that the image did exist and could be opened  normally.

At first I thought it was bug of ghost and create an issuse [here](https://github.com/TryGhost/Ghost/issues/10417) but it was closed because they treat it as a sipport.

### Screenshot

![]()
![image](https://user-images.githubusercontent.com/20741596/53939473-19c13f80-40ee-11e9-9d23-e593f0e4e06c.png)

### Steps to Reproduce

 1. lauch ghost using docker-compose
  ```
docker network create --driver bridge ghost_default --subnet 10.0.1.0/24

cat > docker-compose.yaml << EOF
version: '3.1'
services:
  ghost:
    image: ghost:2.10
    restart: always
    container_name: ghost
    ports:
      - 3001:2368
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: xxxxyyyy
      database__connection__database: ghost
      url: http://www.itsfun.tk
    volumes:
      - ./ghost-data:/var/lib/ghost/content
    network_mode: bridge
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xxxxyyyy
    network_mode: bridge
EOF
```
This works fine.

 2. Changed the ghost image version to `image: ghost:2.11` or newer

Image corrupted.

3. Kept the image changed and reset the Casper to version `casper-2.8.1` at admin page under Design

Image loaded normally.

So I think it's a bug of Casper, or maybe it's not compatible with ghost api v2, see change log:  
https://github.com/TryGhost/Casper/releases/tag/2.9.0

### Technical details

* Casper Version: >= v2.9.0
* Ghost Version: >= 2.11
* Browser Version:  Cent Browser Version 3.8.5.69 (64-bit) (Chromium 71.0.3578.98)
* OS Version: Win10

### Let me know why if you think its a supporting issue before closing it

Thanks a lot for your great working.
