### ISSUE TITLE
Short code blocks are wrapped by characters always (in the end of line)

### ISSUE THREAD

**Issue by fadeevab** [TryGhost/Casper#605]
After closing the issue https://github.com/TryGhost/Casper/issues/466, the words in the code block are wrapped hardly by each symbol even in simple situations.

### Screenshot
![image](https://user-images.githubusercontent.com/5967447/62574976-5c0bca00-b8a2-11e9-894b-f98a8becc355.png)

**st-ruct**

More:

![image](https://user-images.githubusercontent.com/5967447/62557292-61a3e880-b87f-11e9-9b9b-5d4d94de0946.png)

**dat-a**

### Technical details

* Casper Version: 2.10.6
* Ghost Version: 2.27.0
* Browser Version: Firefox 68
* OS Version: Windows

**Comment by fadeevab** [comment]
I use Code Injection feature to overcome this behavior:
```css
    /* Workaround over https://github.com/TryGhost/Casper/issues/466 */
    .post-full-content p code {
        word-break: break-word;
    }
```
