### ISSUE TITLE
#fragment link targets are obscured by floating top nav

### ISSUE THREAD

**Issue by cbeams** [TryGhost/Casper#749]
### Background
The bug described at the link below is now fixed on my own site at https://blog.beams.io, but can still be reproduced on any Ghost site running a recent version of Casper. For example, https://blog.lopp.net/bitcoin-2020-annual-review/#general-interest still exhibits the reported behavior. Note the #fragment link and how the heading is hidden from view under the top nav. The screenshot below shows the same.

Please see https://lab.beams.io/services/blog/-/issues/3 for complete details including the solution we implemented to fix the problem, which looks like the following and is explained in detail [here](https://lab.beams.io/services/blog/-/issues/3#note_53):

```css
.post-content h2 {
    padding-top: 80px;
    margin-top: -54.4px !important;
}
.post-content h3 {
    padding-top: 80px;
    margin-top: -67.5px !important;
}
.post-content a {
    position: relative;
    z-index: 99
}
```

I'm code-injecting this on my site as an inline `<script>` and did not attempt to issue a pull request against `screen.css`/`global.css` because I'm sure the maintainers here will have a better way of implementing this change.

In any case, I hope this fix is something that can be integrated into Casper proper.

### Screenshot

![image](https://user-images.githubusercontent.com/301810/105318783-3ec8d980-5bc4-11eb-9d95-6aff17fc5128.png)

### Steps to Reproduce
 
See repro steps in the issue linked above.

### Technical details

* Casper Version: 3.1.2
* Ghost Version: v3.40.5
* Browser Version: Firefox 84.0.2
* OS Version: macOS 10.15.7
