### ISSUE TITLE
v5.0.0 Background Color in header does not appear on home page

### ISSUE THREAD

**Issue by jcgallaher** [TryGhost/Casper#862]
If I upgrade to v5.0.0 I have some CSS code injection for background Color in the header/navigation area that no longer appears on the home page with a background image. However, it shows up on the other pages.

Here's a sample of my CSS code:
```
/* Add background color to header navigation */
    .home-template .gh-head.has-cover {
		background: var(--ghost-accent-color);
}
```

**Comment by minimaluminium** [comment]
Hey @jcgallaher, the `.has-cover` class has been lifted up to the `<body>` element to cover more element states other than `.gh-head`.

You'll be able to achieve the same result by removing `.has-cover` from the CSS. It'd be something like:

```css
/* Add background color to header navigation */
.home-template .gh-head {
    background: var(--ghost-accent-color);
}
```
